### ISSUE TITLE
Automatiser la mise à jour des données

### ISSUE THREAD

**Issue by clairezed** [clairezed/guide-conso#14]

**Comment by clairezed** [comment]
Ressources : 
- Update a file : https://developer.github.com/v3/repos/contents/#update-a-file
- [Working with Github repository files using Google Apps Script: Examples in getting, writing and committing content](https://mashe.hawksey.info/2016/08/working-with-github-repository-files-using-google-apps-script-examples-in-getting-writing-and-committing-content/)
- [Github API Examples with Google Apps Script](https://script.google.com/d/1jI_BpCFqKstGFQ8sNY8nJwjOiXXhubKDvD7G9h6U1iE63mzX2e4U-ak_/edit?usp=sharing)

**Comment by DavidBruant** [comment]
Je me permets de retranscrire un morceau de conversation que je ne vois pas ici

Parmi les options possibles, il y avait : 
- le code du Google Script fasse une PR 
- le code du Google Script commit directement sur `master`

@clairezed préfère le commit direct, parce que les PR nécessiterait une étape de validation des PR sur github qu'elle devrait gérer. Et donc elle serait un goulot d'étranglement, ce qui n'est pas souhaitable à ce stade.

Le fait de commiter directement par appels d'API amène le risque de réécriture d'histoire, etc. Afin d'éviter ça, nous avons [protégé la branche master](https://help.github.com/articles/about-protected-branches/) sur ce repo

**Comment by DavidBruant** [comment]
Sur la question de stocker des informations secrètes (token github) dans le script, tu peux utiliser les 
[Script Properties](https://developers.google.com/apps-script/guides/properties#comparison_of_property_stores)
 
Dans le projet google app script, tu peux créer des script property à la main en allant dans "Fichier" => "Propriétés du projet" : 
![capture d ecran de 2018-06-14 11-20-41](https://user-images.githubusercontent.com/165829/41403457-367df992-6fc5-11e8-9306-2f95e4408550.png)
