### ISSUE TITLE
Supprimer le backlog général

### ISSUE THREAD

**Issue by DavidBruant** [clairezed/guide-conso#15]
Après discussion avec Romain (mon coloc) : https://github.com/DavidBruant/scrum-a-la-sauce/issues/5

Ptèt que le backlog général, il sert à rien. Et notre utilisation quand on était dans la même pièce montrait que maintenir les deux était parfois redondant (rajouter une issue au sprint, ce qui mène à la bouger vers le doing du backlog général, mais avec une valeur discutable)

On en papote quand le moment est pertinent

**Comment by clairezed** [comment]
Plutôt d'accord avec ça sur le principe. Sauf que ça implique : 
- de directement créer des issues, et non des notes
- donc de pas avoir d'endroit où poser des ptites notes en vrac qu'on peut détruire sans scrupule (vu que tout ce qu'on peut faire pour des issues, c'est de les fermer, et ça reste dans l'historique).

Contre proposition -> garder un backlog général de feignasse : 
- il sert principalement à stocker des notes en vrac
- quand on entame un sprint, on convertit les notes qu'on veut traiter en issues et on en précise le contenu
- on ne change pas de colonne les issues du backlog général, on manipule juste les issues dans le sprint (parce que je vois pas comment automatiser un passage dans la colonne Doing dans le backlog général)
- on automatise dans backlog la colonne Done, pour que les issues fermées y aillent automatiquement

Un truc du genre.

Je devrais avoir un moment jeudi matin pour en discuter de vive voix, si besoin

**Comment by DavidBruant** [comment]
On a rajouté de l'automatisation et c'est bon pour le moment, on garde le backlog général
